services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  finka-rest:
    environment:
      - POSTGRESDB_HOST=postgresdb
      - POSTGRESDB_PORT=5432
    container_name: finka-rest
    ports:
      - "3000:3000"
    build: .
    command: sh -c "npx sequelize-cli db:migrate && npm start"
    depends_on:
      - postgresdb

volumes: 
  db:
