FROM node:20.12.1 as backend
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY .sequelizerc ./
COPY .env.production ./
RUN npm install --production
RUN npm install sequelize-cli
COPY . .

EXPOSE 3000
CMD ["npm", "start"]