services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  # finka-rest:
  #   container_name: finka-rest
  #   ports:
  #     - "3000:3000"
  #   build: .
  #   develop:
  #     watch:
  #       # - action: sync+restart
  #       - action: sync
  #         path: ./src
  #         target: /app/src

  #       - action: rebuild
  #         path: package.json
  #         target: /app

volumes: 
  db:
