name: Deploy to DigitalOcean

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  cd finka-rest/ &&
            git pull origin main &&
            docker-compose -f docker-compose.prod.yml build --no-cache &&
            docker-compose -f docker-compose.prod.yml up -d
